In [1]:
import tensorflow as tf

## 02. 균등 분포 난수

일반적으로 각 이벤트의 결과값을 알 수 없는 경우 미래에 발생할 이벤트의 결과값 
가 각 예상되는 범위별로 균등한 확률로 일어날 것이라고 예상될 때 사용.

### 1) 균등 분포 난수의 사용 예
#### 주사위에 대한 확률
- 200번을 던지고 201번째  주사위를 던진다고 했을 때 201번째 결과값은 앞의 1에서 200번까지 결과값에 영향을 받지 않는다.
- 201번째 결과값이 1,2,3,4,5,6 각각의 결과값으로 나올 확률은 6분의 1이며 이는 앞의 1~200번째 결과값에 영향을 받아 줄어들거나 늘어나지 않는다는 것이다.
- 이처럼 미래 결과값이 경험적으로 알 수 없을 상황에서 사용하는 것이 균등분포이다.
### 2) 균등 분포 난수 실험
#### 스칼라 형태의 균등 분포 난수


In [9]:
uni_rnd1 = tf.random.uniform(shape=[],minval = 0, maxval = 100, dtype= tf.int32)
tf.print(uni_rnd1)

77


#### 백터 형태의 균등 분포 난수

In [2]:
uni_rnd2 = tf.random.uniform(shape=[5], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd2)

[95 7 13 29 74]


#### 행렬 형태의 균등 분포 난수

In [11]:
uni_rnd3 = tf.random.uniform(shape=[2, 3], minval = 0, maxval = 100, dtype = tf.int32)
tf.print(uni_rnd3)

[[26 38 25]
 [28 74 98]]


#### 텐서 형태의 균등 분포 난수

In [14]:
uni_rnd4 = tf.random.uniform(shape=[2, 3 ,4], minval = 0, maxval = 100, dtype = tf.int32)
tf.print(uni_rnd4)

[[[37 28 26 89]
  [31 47 2 19]
  [96 31 30 64]]

 [[4 50 38 43]
  [68 71 13 51]
  [57 40 70 30]]]


### 3) 렌덤값을 갖는 행렬 곱 예시
#### 랜덤값을 갖는 3행2열의 행렬을 변수 x로 정의


In [15]:
x = tf.Variable(tf.random.uniform([3, 2]))
tf.print(x)


[[0.783233047 0.339364886]
 [0.955718279 0.699849963]
 [0.326861501 0.758394361]]


#### 랜덤값을 갖는 2행1열의 행렬을 변수 y로 정의

In [16]:
y = tf.Variable(tf.random.uniform([2, 1]))
tf.print(y)


[[0.0527613163]
 [0.530131936]]


#### 행렬곱에 대한 연산을 수행하는 노드 정의

In [17]:
expr = tf.matmul(x, y)
expr

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.22123258],
       [0.42143777],
       [0.41929471]], dtype=float32)>

## 03. 정규 분포 난수
정규분포란 과거의 축적된 경험적 데이터를 이미 보유하고 있는 상태에서 이용하여 미래에 발생할 결과값 
의 각 예상되는 범위별로 발생될 확률을 어느 정도 추정할 수 있을 때 사용

### 1) 정규 분포 난수의 사용 예
#### 매장의 매출액 예측
- 이전 3개월의 매출이 2천만원, 2천백만원, 2천2백원 발생한 경우 평균이나 범위에 대한 예측이 가능하다.
- 평균에 대한 예측 → 이번달 매출은 과거 3개월의 매출평균인 2천백만원으로 예측.
- 범위에 대한 예측 → 최소 2천만원 ~  최대 2천2백만원까지 매출이 발생할 수 있다는 예상이 가능함.

#### 로또 추첨
- 64개의 공 중에서 하나를 랜덤으로 추출하면, 두 번째 랜덤 범위는 첫 번째 추출된 공을 제외한 범위 안에서 생성된다.
- 만약 로또 추첨시 하나의 공을 뽑아 번호를 확인하고 그 공을 다시 추첨 대상에 포함시켰다면 균등분포 난수가 된다.
### 2) 정규 분포 난수 실험
정규 분포 난수를 생성할 때는 평균(mean)과 표준편차(stddev)를 지정해야 한다.

#### 스칼라 형태의 정규 분포 난수

In [18]:
normal_rnd1 = tf.random.normal(shape=[], mean=0.0, stddev=1.0)
tf.print(normal_rnd1)

0.362656534


#### 백터 형태의 정규 분포 난수

In [39]:
uni_rnd2 = tf.random.normal(shape=[5], mean=0.0, stddev=1.0)
tf.print(uni_rnd2)


[0.64469856 -0.791777074 0.0967347 2.36336136 0.117465913]


#### 행렬 형태의 정규 분포 난수

In [40]:
normal_rnd3 = tf.random.normal(shape=[2,3], mean=0.0, stddev=1.0)
tf.print(normal_rnd3)        

[[0.474039 0.685015261 2.78343225]
 [-0.414915979 -0.659171522 0.639701843]]


#### 텐서 형태의 정규 분포 난수

In [41]:
normal_rnd4 = tf.random.normal(shape=[2,3,4], mean=0.0, stddev=1.0)
tf.print(normal_rnd4)

[[[-0.164383128 -1.57331026 -0.167570159 -0.572207272]
  [-0.0652373135 -0.461083472 0.300094098 -0.849888742]
  [1.50635517 1.73133898 0.329100311 -1.48078549]]

 [[0.159701794 -0.192494929 -0.26984176 -0.583861291]
  [-1.76132596 -0.348786175 -1.46203744 -0.848909795]
  [0.176924393 0.745863318 1.73027587 -0.248933375]]]
