In [2]:
import numpy

In [4]:
arr = numpy.array([1,3,5,7,9])
arr

array([1, 3, 5, 7, 9])

In [6]:
size = len(arr)
print(size)

5


In [8]:
print(arr[0])

1


In [10]:
for i,v in enumerate(arr):
    print("%d번쨰 원소 >> %d" % (i,v) )

0번쨰 원소 >> 1
1번쨰 원소 >> 3
2번쨰 원소 >> 5
3번쨰 원소 >> 7
4번쨰 원소 >> 9


In [11]:
# 파이썬의 리스트는 서로 다른 타입 허용
arr2 = [1,2,3, '4']
arr2

[1, 2, 3, '4']

In [13]:
# 모든 원소의 타입을 강제로 int(정수)로 지정
# -> 소수점 아래 값들은 모두 버려진다.
arr5 = numpy.array([1,2.4,3,4.6], dtype ='int')
arr5

array([1, 2, 3, 4])

In [15]:
grade = numpy.array([82,77,91,88])
grade

array([82, 77, 91, 88])

In [17]:
s1 = numpy.sum(grade)
print("총점: %d" %s1)

총점: 338


In [19]:
# 모든 원소의 평균
s2 = numpy.average(grade)
print("평균 : %d" % s2)

평균 : 84


In [20]:
# 최대 최소
s3 = numpy.max(grade)
s4 = numpy.min(grade)
print('최대값 : %d, 최소값: %d' %(s3, s4))

최대값 : 91, 최소값: 77


In [21]:
new1 = grade +2
new1

array([84, 79, 93, 90])

In [22]:
new2 = grade -5
new2

array([77, 72, 86, 83])

In [24]:
arr1 = numpy.array([10,15,20,25,30])
arr2 = numpy.array([2,3,4,5,6])


In [26]:
a = arr1 + arr2
a

array([12, 18, 24, 30, 36])

In [28]:
b = arr1 - arr2
b

array([ 8, 12, 16, 20, 24])

In [30]:
c = arr1 * arr2
c

array([ 20,  45,  80, 125, 180])

In [32]:
d = arr1 / arr2
d

array([5., 5., 5., 5., 5.])

In [33]:
arr1 = numpy.array([10,15,20,25,30])
arr2 = numpy.array([2,3,4,5,6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [35]:
a = numpy.add(arr1, arr2)
a

array([12, 18, 24, 30, 36])

In [37]:
b = numpy.subtract(arr1,arr2)
b

array([ 8, 12, 16, 20, 24])

In [38]:
c = numpy.multiply(arr1, arr2)
c

array([ 20,  45,  80, 125, 180])

In [39]:
d = numpy.divide(arr1, arr2)
d

array([5., 5., 5., 5., 5.])

In [41]:
grade[1:3]

array([77, 91])

In [42]:
grade = numpy.array([
    [98, 72, 80, 64],
    [88, 90, 80, 72],
    [92, 88, 82, 76]
    ])
grade

array([[98, 72, 80, 64],
       [88, 90, 80, 72],
       [92, 88, 82, 76]])

In [43]:
grade.ndim

2

In [44]:
grade.shape

(3, 4)

In [45]:
grade.dtype

dtype('int32')

In [46]:
grade[1,2]

80

In [47]:
grade[1][2]

80

In [48]:
# 각 열끼리 더함 (세로로 덧셈) -> 결과 타입은 numpy의 1차 배열
s1 = numpy.sum(grade,axis = 0)
print(type(s1))
s1

<class 'numpy.ndarray'>


array([278, 250, 242, 212])

In [49]:
# 각 행끼리 더함 (가로로 덧셈)
s2 = numpy.sum(grade, axis =1)
type(s2)
s2

array([314, 330, 338])

In [51]:
# 추출하고자 하는 원본과 같은 사이즈의 배열
# 추출할 값은 True, 그렇지 않으면 False
bool_array = numpy.array([
    [True, False, True, False],
    [True, True, True, False],
    [True, True, True, False]
])
result1 = grade[bool_array]
result1

array([98, 80, 88, 90, 80, 92, 88, 82])

In [52]:
result2 = grade[grade>= 80]
result2

array([98, 80, 88, 90, 80, 92, 88, 82])

In [53]:
result3 = grade[numpy.logical_and(grade >= 80, grade <= 90)]
result3

array([80, 88, 90, 80, 88, 82])

In [1]:
items = [10,30,50,70,90]

In [5]:
import pandas as pd
column = pd.Series(items)

In [6]:
column

0    10
1    30
2    50
3    70
4    90
dtype: int64

In [8]:
# -> 시리즈의 값들을 저장하고 있는 numpy 배열을 list로 변환
value_list = list(column.values)
value_list

[10, 30, 50, 70, 90]

In [9]:
column.index

RangeIndex(start=0, stop=5, step=1)

In [11]:
pd.RangeIndex(start=0, stop=5, step=1)

RangeIndex(start=0, stop=5, step=1)

In [13]:
type(column.index)

pandas.core.indexes.range.RangeIndex

In [14]:
# 시리즈의 색인(index)를 list로 변환
mylist = list(column.index)
mylist

[0, 1, 2, 3, 4]

In [16]:
# 특정 조건에 마즌 항목들만 추출
int1 = column[column > 30]
int1

2    50
3    70
4    90
dtype: int64

In [17]:
# 70이하 and 10초과인 항목들만 추출
in2 = column[column <= 70][column > 10]
in2

1    30
2    50
3    70
dtype: int64

In [22]:
# 인덱스를 직접 지정하면서 시리즈 만들기
# -> 지난 주 주말에 대한 매출액
week1 = pd.Series([290000,310000], index = ['sat', 'sun'])
print(week1)
print("-" *30)
week2 = pd.Series([120000,220000], index = ['sat', 'sun'])
print(week2)
print("-" *30)
merge = week1+week2
print(merge)


sat    290000
sun    310000
dtype: int64
------------------------------
sat    120000
sun    220000
dtype: int64
------------------------------
sat    410000
sun    530000
dtype: int64
